name = "hyde-hyde-hyde"
license = "MIT"
licenselink = "https://github.com/gamingrobot/hyde-hyde-hyde/blob/master/LICENSE.md"
description = "A simply cool Hyde inspired theme"
tags = ["blog", "theme", "hyde", "google analytics", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "responsive",]
homepage = "https://github.com/gamingrobot/hyde-hyde-hyde"
min_version = "0.43"

[author]
    name = "gamingrobot"
    homepage = ""

# If Porting existing theme
[original]
    author =  "htr3n"
    homepage = "https://htr3n.github.io"
    repo = "https://github.com/htr3n/hyde-hyde"
